const SIGN_IN = "SIGN_IN";
const SIGN_UP = "SIGN_UP";
const GET_ERRORS = "GET_ERRORS";
const CLEAN_ERRORS = "CLEAN_ERRORS";
const GET_PROFILE = "GET_PROFILE";

const GET_CODE = "GET_CODE";
const GET_PRODUCTS  =  "GET_PRODUCTS";
const SET_PRODUCT = "SET_PRODUCT";
const CHANGE_LANGUAGE = "CHANGE_LANGUAGE";



export {
    SIGN_IN,
    SIGN_UP,
    GET_ERRORS,
    CLEAN_ERRORS,
    GET_CODE,
    GET_PRODUCTS,
    SET_PRODUCT,
    GET_PROFILE,
    CHANGE_LANGUAGE
}